


POST http://localhost:8800/auth/signup

content-type: application/json
{
    "email":"rh6@gmail.com",
    "password":"12345x678"
}
PATCH   http://localhost:8800/auth/2

{
  "email":"abi@gmail.com"
}

GET http://localhost:8800/auth/2







Delete http://localhost:8800/auth/3



GET http://localhost:8800/auth/1




  






