
GET http://localhost:8800/auth/2


PATCH   http://localhost:8800/auth/2

{
  "email":"abishek@gmail.com"
}

Delete http://localhost:8800/auth/3


POST http://localhost:8800/auth/signup

content-type: application/json
{
    "email":"aashish566@gmail.com",
    "password":"12345x678"
}

GET http://localhost:8800/auth/1




  






